### ISSUE TITLE
[BUG] Storybook link broken, wrong npm script command

### ISSUE THREAD

**Issue by mbmjertan** [infinum/eightshift-docs#113]
## Describe the bug

- [ ] The Storybook link on [the Storybook docs page](https://infinum.github.io/eightshift-docs/storybook/) is broken, leading to https://infinum.github.io/eightshift-docs/docs/basics/blocks-storybook instead of https://infinum.github.io/eightshift-docs/storybook/

- [ ] `npm run Storybook` isn't a valid command, it should be replaced with `npm run storybook`

## Additional context

I'd fix this myself, but I'm not sure what branch to branch off of.

**Comment by iruzevic** [comment]
this is fixed in the release 6
