### ISSUE TITLE
Make sidebar sticky and collapsed on sass docs

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#162]
### Describe your feature request

Currently clicking on any of the links in the sidebar here: https://infinum.github.io/eightshift-docs/sass will scroll you to that part of sass docs, but the sidebar stays at the top, which is not ideal from a UX point of view.

### Describe the solution you'd like

Having the headings collapsed would allow us to have this sidebar sticky on the desktop resolutions when scrolling the content.

### Environment info

- N/A

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
done
