### ISSUE TITLE
Remove environment info from the feature request and question issue template

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#163]
### Describe your feature request

The env info should only be present in the bug report issue, not all of them. I think the same was copied over to other templates on other eightshift repos.

Can you fix this?

Thanks

### Describe the solution you'd like

Remove environment info from feature request and questions.

In fact, questions issue should be removed alltogether, or point to discussions. You can check out how I did it in https://github.com/infinum/eightshift-coding-standards/issues/new/choose

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
done
