### ISSUE TITLE
Should the issues from the frontend libs and libs be transferred here?

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#17]
There are lots of issues in both libs

https://github.com/infinum/eightshift-libs/issues
https://github.com/infinum/eightshift-frontend-libs/issues

Should all of these be transferred here?

@infinum/eightshift-team

**Comment by IvanGrginovInf** [comment]
@dingo-d why since they're not related to docs but rather the libs themselves?

**Comment by iruzevic** [comment]
Agreed we should keep the issues in the lib that is the issue refers to

**Comment by dingo-d** [comment]
Oh, I thought that issues are mostly docs related, my bad :+1:
