### ISSUE TITLE
Add pagination and footer to the block article listing page

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#185]
### Describe your feature request

The title says it all.

The pagination isn't showing on the article listing page, and the footer should be added like in the showcase page.

### Describe the solution you'd like

In the feature request.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
added
