### ISSUE TITLE
Improve issue templates

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#186]
### Describe your feature request

The current templates are not suited for the docs project. They are ok for the libs.

### Describe the solution you'd like

They should be simpler. It makes no sense to have some options in the bug template, as well as in the feature section (like PHP version etc.)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
done
