### ISSUE TITLE
Documentation missing for storybook setup

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#188]
### Describe your bug

When you set up a theme, you get the `.storybook` folder, but the instructions are missing to install a package `@eightshift/storybook`.

### Steps to Reproduce

Try to run the storybook, and watch nothing happen

### Expected behavior

We need instructions about the package in the docs, and a notice in the WPCLI command

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
storybook is removed in the latest release so I will close this
