### ISSUE TITLE
Storybook is throwing errors on icon components

### ISSUE THREAD

**Issue by gabriel-glo** [infinum/eightshift-docs#189]
### Describe your bug

When trying to view the Storybook icons: https://eightshift.com/storybook/, we get the following error:

```
(0 , emotion_core_cjs.jsx) is not a function

TypeError: (0 , emotion_core_cjs.jsx) is not a function
    at BlockIcons (https://infinum.github.io/eightshift-frontend-libs/storybook/main.6ee26c2e.iframe.bundle.js:2:1469761)
    at undecoratedStoryFn (https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:1237870)
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:136427
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:1229801
    at jsxDecorator (https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:1196239)
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:136427
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:1230056
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:1229801
    at https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:73385
    at withActions.name (https://infinum.github.io/eightshift-frontend-libs/storybook/273.c05ef810.iframe.bundle.js:2:73569)
```

### Steps to Reproduce

1. Navigate to https://eightshift.com/storybook/
2. Select Icons > Block Icons, Helper Illustrations or UI Icons from the sidebar menu.

### Expected behavior

View all available icons in grid layout

### Screenshots, screen recording, code snippet

![image](https://user-images.githubusercontent.com/41635034/181482479-6ea87a12-a617-4cc8-928f-5417ada12914.png)

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by iruzevic** [comment]
fixed
