### ISSUE TITLE
Fix broken links on blocks faq page

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#203]
### Describe your bug

There are 20 broken links on the faq page

### Steps to Reproduce

Go to https://eightshift.com/docs/basics/blocks-faq/ and find all the broken links

### Expected behavior

Links should work

### Screenshots, screen recording, code snippet

<img width="729" alt="image" src="https://user-images.githubusercontent.com/8638515/197968641-2591e98f-3181-408f-8024-cfaf0a0d3535.png">

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Tried it out locally with the latest from the `develop` branch, seems fine 🤷

**Comment by dingo-d** [comment]
@goranalkovic-infinum I can confirm. I guess the report was a local bug that was reported 🤷🏼‍♂️ 

Sorry for wasting your time.
