### ISSUE TITLE
Improve backend docs

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#204]
### Describe your feature request

We should write a bit more about the backend part, service classes, why we are using them and how they are used.

### Describe the solution you'd like

A bit more explanation on why the service classes approach is used

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
we have a duplicate issue for this
