### ISSUE TITLE
Make pagination more visible

### ISSUE THREAD

**Issue by dadadavorin** [infinum/eightshift-docs#232]
### Describe your feature request

We should probably show more than 6 entries on a blog homepage. I had some trouble finding the post about adding fonts and took me some time to realize there is a button with the label "Older entries" at the bottom right.

Also, adding load more and loading posts with AJAX would be nice improvement.

(not sure if @dingo-d was also referring to that on the block article issue)

### Describe the solution you'd like

Show at least 12 posts and add more visible and user friendly pagination, preferably load more.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iruzevic** [comment]
are you referring to this URL? 
https://eightshift.com/blog/

**Comment by iruzevic** [comment]
step-by-step guide on how to set up REST routes
explanation of the whole process how to build Load More component and use it
it will have to be published in multiple parts

**Comment by iruzevic** [comment]
We will not use load more because it would be to much work. 
@goranalkovic-infinum please just make pagination little bigger or more visible, tnx
