### ISSUE TITLE
i18n in a project

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-docs#258]
### Describe your feature request

explanation how to set up i18n a project
recommend plugins for i18n
additional tips & tricks, like fetching ACF Theme Options in a specific language

https://infinum.github.io/eightshift-docs/docs/basics/tips-tricks/#internationalization-i18n-and-localization-l10n

### Describe the solution you'd like

.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

**Comment by iobrado** [comment]
This is published:
https://eightshift.com/blog/making-your-project-multilingual
