### ISSUE TITLE
Make storybook/scss background the same color as header and foorer

### ISSUE THREAD

**Issue by iruzevic** [infinum/eightshift-docs#264]
### Describe your bug

Make storybook background the same color as header and foorer

### Steps to Reproduce

.

### Expected behavior

.

### Please confirm that you have searched existing issues in this repo.

Yes

### Please confirm that you have searched in our documentation and couldn't find the answer.

Yes

### Please confirm that your bug occurs with all plugins uninstalled and with the default WordPress theme active.

Yes

**Comment by goranalkovic-infinum** [comment]
Fixed recently
