### ISSUE TITLE
[FEATURE] - Auto Collapsible Sidebar

### ISSUE THREAD

**Issue by himanshu-03** [infinum/eightshift-docs#275]
### Use case description

| Use case | Description |
| :--- | :--- |
| Overwhelming Navigation | The vast array of categories shown in the sidebar may be too much for new website visitors to handle. It is preferable to have the sidebar open for the sole category in which the user is interested |
| Scrolling Fatigue | If there are numerous categories in the sidebar, users may need to scroll extensively to find the specific category or content they are interested in, leading to scrolling fatigue. |
| Lack of Personalization | Users may want to customize their navigation experience by collapsing or prioritizing certain categories, which is not possible with a fixed sidebar |

### Proposed solution

Modifying the Docusaurus configuration file (typically docusaurus.config.js) to enable the collapsible sidebar feature will help us in solving this issue. It can be achieved by adjusting settings related to the sidebar in the configuration.

| Present Scenario | Post Scenario (Proposed Solution) |
| :-- | :-- |
| <img src="https://github.com/infinum/eightshift-docs/assets/97957777/ecd7828b-bf16-4fa7-9d8b-d59f39a164b0" width=200> | <img src="https://github.com/infinum/eightshift-docs/assets/97957777/f8856e2c-8ea6-48a6-afec-8676359f82f4" width=200> |
| Currently, when I click on the `Basics` category, it expands to reveal its subcategories. However, if I then want to navigate to the `Migrations` category, and I click on it, the sidebar for the `Basics` category remains open and doesn't collapse automatically. This can make it confusing to navigate the sidebar efficiently. | In the improved scenario, when I click on the `Basics` category, it will expand to reveal its subcategories just like before. However, if I then want to navigate to the `Migrations` category and click on it, the sidebar for the `Basics` category will automatically collapse. This enhancement will make navigation more intuitive and efficient. |

**Comment by himanshu-03** [comment]
I was thinking if I can work on this issue?

**Comment by iruzevic** [comment]
If you are interested in trying to fix this, I see no reason not to :D thx for your help and support

**Comment by himanshu-03** [comment]
Hey @iruzevic ! Just had a doubt

Will this issue be part of the hacktoberfest 2023 contributions?

**Comment by iruzevic** [comment]
I have no idea, this is a public repo. Maybe @goranalkovic-infinum will know?

**Comment by himanshu-03** [comment]
Hey @iruzevic !
can you please review my PR here: #277 

Also, if it can be counted towards hacktoberfest, that would be great!

**Comment by iruzevic** [comment]
Tnx @himanshu-03, for your contribution. Your PR is merged to the main and deployed to our documentation pages
