### ISSUE TITLE
List of code examples

### ISSUE THREAD

**Issue by IvanGrginovInf** [infinum/eightshift-docs#6]
A working list of examples we should write at some point. If you're working on one you should open a new issue and assign it to yourself.

Also feel free to add example ideas here:

- [x] Register custom post type
- [ ] Register custom taxonomy
- [ ] Use custom fonts
- [ ] Copy existing block / component
- [ ] Add new block / component
- [ ] Disable core blocks (only allow our custom blocks)
- [x] Use of DI container (libs)

**Comment by iruzevic** [comment]
https://github.com/infinum/eightshift-docs/issues/7

**Comment by iruzevic** [comment]
https://github.com/infinum/eightshift-docs/issues/8

**Comment by dingo-d** [comment]
#16 - DI chapter added

**Comment by iruzevic** [comment]
all the bullets are in the docs so I will close it and we will open an individual ticket when starting to write
