### ISSUE TITLE
[BUG] Search seems to be broken

### ISSUE THREAD

**Issue by dingo-d** [infinum/eightshift-docs#64]
No matter what I search for, it looks broken and returns page not found 🤷🏼‍♂️ 

https://user-images.githubusercontent.com/8638515/105713628-aa3fdd80-5f1b-11eb-90cf-7e2ad63dc2e0.mov

**Comment by simun-ivanac** [comment]
@iruzevic, @dingo-d It looks like this is fixed. Can you please check it out so I can close it?

**Comment by iruzevic** [comment]
It looks like it is fixes, maybe Alegoria reindexed or something.

If @dingo-d confirms you can close this issue

**Comment by dingo-d** [comment]
Fixed
