### ISSUE TITLE
[FEATURE] New graphics for the Eightshift universe repos

### ISSUE THREAD

**Issue by goranalkovic-infinum** [infinum/eightshift-docs#85]
As discussed, this issue covers creating new graphics to represent Eightshift in repos and on social networks.

This is the current illustration:
![image](https://user-images.githubusercontent.com/77000136/115549553-0f9c3400-a2a9-11eb-97bb-5a80fb2ce024.png)

We need these:
- [ ] Eightshift libs
- [ ] Eightshift frontend libs
- [ ] Eightshift boilerplate
- [ ] Eightshift boilerplate plugin
- [ ] Eightshift docs
- [ ] Eightshift forms
- [ ] Eightshift starter task?

**Comment by iruzevic** [comment]
done
